# Generated by Django 4.1.11 on 2023-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Email')),
                ('fullName', models.CharField(max_length=100, unique=True)),
                ('organization', models.CharField(max_length=100)),
                ('otp', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('team_leader', models.BooleanField(default=False)),
                ('technical_support', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
                ('labeler', models.BooleanField(default=False)),
                ('reviewer', models.BooleanField(default=False)),
                ('approver', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
